version: '3.1'
services:
  fastapi:
    image: app
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - custom
  postgres:
    image: postgres
    container_name: "my_postgres"
    environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  pg_data:
